services:
  - type: web
    name: tts-voice-call-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ELEVENLABS_API_KEY
        value: sk_9006b80a1beaa0d6489e5e3d4ff86b12eeef0b14729aa8d8
      - key: ELEVENLABS_VOICE_ID
        value: uyfkySFC5J00qZ6iLAdh
      - key: GEMINI_API_KEY
        value: AIzaSyDBFlxfPjFDUdTAOnhocXgC4vBGEWfgk14
      - key: PORT
        value: 10000
